package launchers

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"

	"bellum-installer/pkg/core"
)

// LauncherConfig holds configuration for launcher generation
type LauncherConfig struct {
	Wineprefix string
	Protonpath string
	GPUType    string
	IconPath   string
}

// GenerateLauncher generates the launcher wrapper scripts and desktop files.
// Both GPU types write to /usr/local/bin/Bellum, but with different content:
//   - AMD: wine wrapper (wineboot + wine)
//   - NVIDIA: proton wrapper (wineserver + proton run)
func GenerateLauncher(config LauncherConfig) error {
	if err := generateLauncherWrapper(config); err != nil {
		return fmt.Errorf("failed to generate launcher wrapper: %w", err)
	}

	// Generate .desktop files and icon (common to both GPU types)
	if err := generateDesktopFiles(config); err != nil {
		return fmt.Errorf("failed to generate desktop files: %w", err)
	}

	return nil
}

// generateLauncherWrapper creates the /usr/local/bin/Bellum wrapper script.
// GPU-specific content:
//   - AMD: uses wineboot + wine (mirrors lib/launcher.sh)
//   - NVIDIA: uses wineserver -k + proton run (mirrors lib/launcher.sh)
func generateLauncherWrapper(config LauncherConfig) error {
	script := generateWrapperContent(config)
	return writeWrapper("/usr/local/bin/Bellum", script)
}

// generateWrapperContent builds the wrapper script content based on GPU type.
func generateWrapperContent(config LauncherConfig) string {
	launcherExe := filepath.Join(config.Wineprefix, "drive_c/users/steamuser/AppData/Local/Astarte Industries/Astarte Launcher/AstarteLauncher.exe")
	protonBin := filepath.Join(config.Protonpath, "proton")

	switch config.GPUType {
	case "AMD":
		return fmt.Sprintf(`#!/bin/bash
# Bellum Launcher Wrapper
# Auto-generated by the Bellum Linux Installer

set -u

LAUNCH_VARS="%s/launch_vars.env"
GAME_DIR="%s"
LAUNCHER_EXE="%s"
PROTON_BIN="%s/proton"

load_launch_vars() {
	if [ -f "$LAUNCH_VARS" ]; then
		set -a
		source "$LAUNCH_VARS"
		set +a
	else
		echo "ERROR: Launch variables file not found: $LAUNCH_VARS" >&2
		exit 1
	fi
}

validate_paths() {
	if [ ! -f "$LAUNCHER_EXE" ]; then
		echo "ERROR: Launcher executable not found: $LAUNCHER_EXE" >&2
		exit 1
	fi

	if ! command -v wine &>/dev/null; then
		echo "ERROR: wine not found or not executable" >&2
		exit 1
	fi
}

run_launcher() {
	cd "$GAME_DIR" || exit 1
	LOG_FILE="$GAME_DIR/launcher.log"

	wineboot "--restart"
	sleep 1

	wine "$LAUNCHER_EXE" "$@" > "$LOG_FILE" 2>> "$LOG_FILE"

	wineboot "--end-session"

	return "$?"
}

main() {
	load_launch_vars
	validate_paths
	run_launcher "$@"
	exit $?
}

main "$@"
`, config.Wineprefix, config.Wineprefix, launcherExe, config.Protonpath)

	case "NVIDIA":
		return fmt.Sprintf(`#!/bin/bash
# Bellum Launcher Wrapper
# Auto-generated by the Bellum Linux Installer
# Optimized for NVIDIA GPUs

set -u

LAUNCH_VARS="%s/launch_vars.env"
GAME_DIR="%s"
LAUNCHER_EXE="%s"
PROTON_BIN="%s"

load_launch_vars() {
	if [ -f "$LAUNCH_VARS" ]; then
		set -a
		source "$LAUNCH_VARS"
		set +a
	else
		echo "ERROR: Launch variables file not found: $LAUNCH_VARS" >&2
		exit 1
	fi
}

validate_paths() {
	if [ ! -f "$LAUNCHER_EXE" ]; then
		echo "ERROR: Launcher executable not found: $LAUNCHER_EXE" >&2
		exit 1
	fi

	if [ ! -x "%s" ]; then
		echo "ERROR: %s not found or not executable" >&2
		exit 1
	fi
}

run_launcher() {
	cd "$GAME_DIR" || exit 1
	LOG_FILE="$GAME_DIR/launcher.log"

	wineserver "-k"
	sleep 1

	%s run "$LAUNCHER_EXE" "$@" > "$LOG_FILE" 2>> "$LOG_FILE"

	return "$?"
}

main() {
	load_launch_vars
	validate_paths
	run_launcher "$@"
	exit $?
}

main "$@"
`, config.Wineprefix, config.Wineprefix, launcherExe, protonBin, protonBin, protonBin, protonBin)

	default:
		return fmt.Sprintf(`#!/bin/bash
# Bellum Launcher Wrapper
# Auto-generated by the Bellum Linux Installer

set -u

LAUNCH_VARS="%s/launch_vars.env"
GAME_DIR="%s"
LAUNCHER_EXE="%s"
PROTON_BIN="%s/proton"

load_launch_vars() {
	if [ -f "$LAUNCH_VARS" ]; then
		set -a
		source "$LAUNCH_VARS"
		set +a
	else
		echo "ERROR: Launch variables file not found: $LAUNCH_VARS" >&2
		exit 1
	fi
}

validate_paths() {
	if [ ! -f "$LAUNCHER_EXE" ]; then
		echo "ERROR: Launcher executable not found: $LAUNCHER_EXE" >&2
		exit 1
	fi

	if ! command -v wine &>/dev/null; then
		echo "ERROR: wine not found or not executable" >&2
		exit 1
	fi
}

run_launcher() {
	cd "$GAME_DIR" || exit 1
	LOG_FILE="$GAME_DIR/launcher.log"

	wineboot "--restart"
	sleep 1

	wine "$LAUNCHER_EXE" "$@" > "$LOG_FILE" 2>> "$LOG_FILE"

	wineboot "--end-session"

	return "$?"
}

main() {
	load_launch_vars
	validate_paths
	run_launcher "$@"
	exit $?
}

main "$@"
`, config.Wineprefix, config.Wineprefix, launcherExe, config.Protonpath)
	}
}

// writeWrapper writes a wrapper script to the specified path.
// If writing to /usr/local/bin/ and not running as root, it uses pkexec to elevate privileges.
func writeWrapper(path, content string) error {
	dir := filepath.Dir(path)

	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	// Check if we need elevated privileges
	if os.Geteuid() != 0 && strings.HasPrefix(path, "/usr/local/bin/") {
		return writeWrapperWithSudo(path, content)
	}

	if err := os.WriteFile(path, []byte(content), 0755); err != nil {
		return fmt.Errorf("failed to write wrapper script: %w", err)
	}

	return nil
}

// writeWrapperWithSudo uses pkexec to write the file with elevated privileges.
func writeWrapperWithSudo(path, content string) error {
	// Get the current user for ownership
	currentUser, err := user.Current()
	if err != nil {
		return fmt.Errorf("failed to get current user: %w", err)
	}

	// Create a temporary file with the content
	tmpFile, err := os.CreateTemp("", "bellum-launcher-*.sh")
	if err != nil {
		return fmt.Errorf("failed to create temporary file: %w", err)
	}
	tmpPath := tmpFile.Name()
	defer os.Remove(tmpPath) // Clean up temp file

	if _, err := tmpFile.WriteString(content); err != nil {
		tmpFile.Close()
		return fmt.Errorf("failed to write to temporary file: %w", err)
	}
	tmpFile.Close()

	// Use pkexec to copy the file to the target location with root privileges
	cmd := []string{"pkexec", "cp", tmpPath, path}
	if err := core.RunCommand(core.RunModeStream, cmd, nil, ""); err != nil {
		return fmt.Errorf("failed to copy launcher with pkexec: %w", err)
	}

	// Make the file executable
	cmd = []string{"pkexec", "chmod", "755", path}
	if err := core.RunCommand(core.RunModeStream, cmd, nil, ""); err != nil {
		return fmt.Errorf("failed to make launcher executable: %w", err)
	}

	// Change ownership to the current user
	chownArg := fmt.Sprintf("%s:%s", currentUser.Username, currentUser.Username)
	cmd = []string{"pkexec", "chown", chownArg, path}
	if err := core.RunCommand(core.RunModeStream, cmd, nil, ""); err != nil {
		return fmt.Errorf("failed to change launcher ownership: %w", err)
	}

	return nil
}

// generateDesktopFiles creates the .desktop files and icon for the launcher.
// Both GPU types use the same binary name "Bellum" and desktop file "Bellum.desktop".
// This mirrors the bash behavior in lib/launcher.sh:
//   - Desktop files go to ~/.local/share/applications/
//   - Desktop files are also copied to ~/Desktop/
//   - Icon goes to ~/.local/share/icons/hicolor/256x256/apps/bellum.png
//   - gio set metadata::trusted is applied if available
//   - update-desktop-database is run if available
func generateDesktopFiles(config LauncherConfig) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get user home directory: %w", err)
	}

	appsDir := filepath.Join(homeDir, ".local", "share", "applications")
	appsIconDir := filepath.Join(homeDir, ".local", "share", "icons", "hicolor", "256x256", "apps")

	var entryComment string
	switch config.GPUType {
	case "AMD":
		entryComment = "Launch Bellum via Wine"
	case "NVIDIA":
		entryComment = "Launch Bellum via Proton (NVIDIA optimized)"
	default:
		return fmt.Errorf("unsupported GPU type for desktop file: %s", config.GPUType)
	}
	entryName := "Bellum"
	entryExec := "Bellum"

	// Install icon
	installedIcon := ""
	if config.IconPath != "" {
		if err := os.MkdirAll(appsIconDir, 0755); err != nil {
			return fmt.Errorf("failed to create icon directory: %w", err)
		}
		iconDest := filepath.Join(appsIconDir, "bellum.png")
		if err := copyFile(config.IconPath, iconDest); err != nil {
			return fmt.Errorf("failed to copy icon: %w", err)
		}
		installedIcon = filepath.Join(appsIconDir, "bellum.png")
	} else {
		// Fallback: no icon
		installedIcon = ""
	}

	// Generate .desktop file
	desktopFile := filepath.Join(appsDir, fmt.Sprintf("%s.desktop", entryName))
	desktopContent := fmt.Sprintf(`[Desktop Entry]
Name=%s
Comment=%s
Exec=%s
Icon=%s
Type=Application
Categories=Game;
Terminal=false
Path=%s
`, entryName, entryComment, entryExec, installedIcon, config.Wineprefix)

	if err := os.WriteFile(desktopFile, []byte(desktopContent), 0755); err != nil {
		return fmt.Errorf("failed to write desktop file %s: %w", desktopFile, err)
	}

	// Copy to ~/Desktop/
	desktopDest := filepath.Join(homeDir, "Desktop", fmt.Sprintf("%s.desktop", entryName))
	if _, err := os.Stat(filepath.Join(homeDir, "Desktop")); err == nil {
		if err := copyFile(desktopFile, desktopDest); err != nil {
			// Non-fatal: desktop directory may not exist or be inaccessible
		}
	}

	// Set write perm
	if err := os.Chmod(desktopDest, 0755); err != nil {
		return fmt.Errorf("failed to make Bellum desktop file executable: %w", err)
	}

	// Mark as trusted via gio if available
	if runtime.GOOS == "linux" {
		_ = runGioSet(desktopFile, "metadata::trusted", "true")
		if _, err := os.Stat(desktopDest); err == nil {
			_ = runGioSet(desktopDest, "metadata::trusted", "true")
		}
	}

	// Update desktop database if available
	if runtime.GOOS == "linux" {
		_ = runUpdateDesktopDatabase(appsDir)
	}

	return nil
}

// runGioSet runs `gio set <file> <key> <value>` silently (non-fatal).
func runGioSet(file, key, value string) error {
	// Create a logger for this operation
	logger, err := core.NewLogger("")
	if err != nil {
		return err
	}
	defer logger.Close()
	return core.RunCommand(core.RunModeSilent, []string{"gio", "set", file, key, value}, logger, "")
}

// runUpdateDesktopDatabase runs `update-desktop-database <dir>` silently (non-fatal).
func runUpdateDesktopDatabase(dir string) error {
	// Create a logger for this operation
	logger, err := core.NewLogger("")
	if err != nil {
		return err
	}
	defer logger.Close()
	return core.RunCommand(core.RunModeSilent, []string{"update-desktop-database", dir}, logger, "")
}

// copyFile copies a file from src to dst
func copyFile(src, dst string) error {
	source, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("failed to open source file: %w", err)
	}
	defer source.Close()

	destination, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("failed to create destination file: %w", err)
	}
	defer destination.Close()

	_, err = destination.ReadFrom(source)
	return err
}

// GenerateLaunchVarsAMD creates the launch variables file for AMD GPUs.
// Writes to ${WINEPREFIX}/launch_vars.env (matching bash behavior).
// isFSR41: true if using FSR 4.1 upgrade path, false for regular mode
func GenerateLaunchVarsAMD(wineprefix string, isFSR41 bool) error {
	return writeLaunchVars(wineprefix, "AMD", isFSR41)
}

// GenerateLaunchVarsFileNvidia creates the launch variables file for NVIDIA GPUs.
// Writes to ${WINEPREFIX}/launch_vars.env (matching bash behavior).
func GenerateLaunchVarsFileNvidia(wineprefix string) error {
	return writeLaunchVars(wineprefix, "NVIDIA", false)
}

// writeLaunchVars creates the launch_vars.env file in the WINEPREFIX.
// The bash version writes this as a plain file (not in a subdirectory).
func writeLaunchVars(wineprefix, gpuType string, isFSR41 bool) error {
	// Determine FSR4 values based on mode
	fsr4Upgrade := "1"
	fsr4Rdna3Upgrade := "1"
	if isFSR41 && gpuType == "AMD" {
		fsr4Upgrade = "4.1.0"
		fsr4Rdna3Upgrade = "4.1.0"
	}

	content := fmt.Sprintf(`# Bellum Launch Variables (%s)
# Auto-generated by Bellum Linux Installer

export __GAMESCOPE_INTEGRATION=""
export __GAMESCOPE_INTEGRATION_FORCE="0"
export __GAMESCOPE_INTEGRATION_GAMER_MODE="0"
export NVAPI_OVERRIDE_CONFIG=""
export NVVM_LIBDIR="${PROTONPATH}/nvvm/lib64"
export LD_LIBRARY_PATH="${PROTONPATH}/lib64:${LD_LIBRARY_PATH}"
`, gpuType)

	// Add FSR4 variables for AMD GPUs
	if gpuType == "AMD" {
		content += fmt.Sprintf(`
export FSR4_UPGRADE="%s"
export FSR4_RDNA3_UPGRADE="%s"
`, fsr4Upgrade, fsr4Rdna3Upgrade)
	}

	return os.WriteFile(filepath.Join(wineprefix, "launch_vars.env"), []byte(content), 0644)
}

// CopyIcon copies the launcher icon to the user's local icon directory
// (matching bash behavior: ~/.local/share/icons/hicolor/256x256/apps/bellum.png)
func CopyIcon(iconPath string) error {
	if iconPath == "" {
		return fmt.Errorf("icon path is empty")
	}

	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get user home directory: %w", err)
	}

	iconDest := filepath.Join(homeDir, ".local", "share", "icons", "hicolor", "256x256", "apps", "bellum.png")
	if err := os.MkdirAll(filepath.Dir(iconDest), 0755); err != nil {
		return fmt.Errorf("failed to create icon directory: %w", err)
	}

	return copyFile(iconPath, iconDest)
}

// DetectLauncherBinary returns the launcher binary name for the given GPU type.
// Both AMD and NVIDIA use the same binary name "Bellum" — the difference is
// in the wrapper content (wine vs proton).
func DetectLauncherBinary(gpuType string) string {
	return "Bellum"
}

// IsLauncherInstalled checks if the launcher binary exists for the given GPU type.
func IsLauncherInstalled(gpuType string) bool {
	binary := DetectLauncherBinary(gpuType)
	if binary == "" {
		return false
	}
	path := filepath.Join("/usr/local/bin", binary)
	_, err := os.Stat(path)
	return err == nil
}

// LauncherBinaryPath returns the full path to the launcher binary for the given GPU type.
func LauncherBinaryPath(gpuType string) string {
	binary := DetectLauncherBinary(gpuType)
	if binary == "" {
		return ""
	}
	return filepath.Join("/usr/local/bin", binary)
}

// LauncherDesktopPath returns the full path to the .desktop file for the given GPU type.
func LauncherDesktopPath(gpuType string) string {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return ""
	}

	binary := DetectLauncherBinary(gpuType)
	if binary == "" {
		return ""
	}
	return filepath.Join(homeDir, ".local", "share", "applications", binary+".desktop")
}

// LauncherIconPath returns the full path to the launcher icon.
func LauncherIconPath(gpuType string) string {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(homeDir, ".local", "share", "icons", "hicolor", "256x256", "apps", "bellum.png")
}

// LaunchVarsEnvPath returns the path to the launch_vars.env file in the WINEPREFIX.
func LaunchVarsEnvPath(wineprefix string) string {
	return filepath.Join(wineprefix, "launch_vars.env")
}

// LauncherExePath returns the path to the AstarteLauncher.exe inside the WINEPREFIX.
func LauncherExePath(wineprefix string) string {
	return filepath.Join(wineprefix, "drive_c/users/steamuser/AppData/Local/Astarte Industries/Astarte Launcher/AstarteLauncher.exe")
}

// LauncherLogPath returns the path to the launcher.log file in the WINEPREFIX.
func LauncherLogPath(wineprefix string) string {
	return filepath.Join(wineprefix, "launcher.log")
}

// EnsureWineBinaries checks that wine, wineboot, and wineserver are available.
// Returns the resolved binary paths.
func EnsureWineBinaries() (wine, wineboot, wineserver string, err error) {
	wine = core.LookPath("wine")
	if wine == "" {
		return "", "", "", fmt.Errorf("wine not found")
	}
	wineboot = core.LookPath("wineboot")
	if wineboot == "" {
		return "", "", "", fmt.Errorf("wineboot not found")
	}
	wineserver = core.LookPath("wineserver")
	if wineserver == "" {
		return "", "", "", fmt.Errorf("wineserver not found")
	}
	return wine, wineboot, wineserver, nil
}

// EnsureProtonBinary checks that the proton binary exists and is executable.
func EnsureProtonBinary(protonpath string) error {
	protonBin := filepath.Join(protonpath, "proton")
	if _, err := os.Stat(protonBin); err != nil {
		return fmt.Errorf("proton binary not found at %s: %w", protonBin, err)
	}
	if err := os.Chmod(protonBin, 0755); err != nil {
		return fmt.Errorf("failed to make proton binary executable: %w", err)
	}
	return nil
}

// GetLauncherScript returns the Bellum wrapper script content (AMD).
func GetLauncherScript(wineprefix, protonpath string) (string, error) {
	wineBin, winebootBin, _, err := EnsureWineBinaries()
	if err != nil {
		return "", err
	}

	return fmt.Sprintf(`#!/bin/bash
# Bellum Launcher Wrapper
# Auto-generated by the Bellum Linux Installer

set -u

LAUNCH_VARS="%s/launch_vars.env"
GAME_DIR="%s"
LAUNCHER_EXE="%s"
PROTON_BIN="%s/proton"

load_launch_vars() {
	if [ -f "$LAUNCHER_EXE" ]; then
		set -a
		source "$LAUNCH_VARS"
		set +a
	else
		echo "ERROR: Launch variables file not found: $LAUNCH_VARS" >&2
		exit 1
	fi
}

validate_paths() {
	if [ ! -f "$LAUNCHER_EXE" ]; then
		echo "ERROR: Launcher executable not found: $LAUNCHER_EXE" >&2
		exit 1
	fi

	if ! command -v %s &>/dev/null; then
		echo "ERROR: %s not found or not executable" >&2
		exit 1
	fi
}

run_launcher() {
	cd "$GAME_DIR" || exit 1
	LOG_FILE="$GAME_DIR/launcher.log"

	%s "--restart"
	sleep 1

	%s "$LAUNCHER_EXE" "$@" > "$LOG_FILE" 2>> "$LOG_FILE"

	%s "--end-session"

	return "$?"
}

main() {
	load_launch_vars
	validate_paths
	run_launcher "$@"
	exit $?
}

main "$@"
`, wineprefix, wineprefix,
		LauncherExePath(wineprefix),
		protonpath,
		wineBin, wineBin,
		winebootBin, wineBin, winebootBin), nil
}

// GetProtonLauncherScript returns the proton wrapper script content (NVIDIA).
func GetProtonLauncherScript(wineprefix, protonpath string) (string, error) {
	wineserverBin := core.LookPath("wineserver")
	if wineserverBin == "" {
		return "", fmt.Errorf("wineserver not found")
	}

	protonBin := filepath.Join(protonpath, "proton")

	return fmt.Sprintf(`#!/bin/bash
# Bellum Proton Launcher Wrapper
# Auto-generated by the Bellum Linux Installer
# Optimized for NVIDIA GPUs

set -u

LAUNCH_VARS="%s/launch_vars.env"
GAME_DIR="%s"
LAUNCHER_EXE="%s"
PROTON_BIN="%s"

load_launch_vars() {
	if [ -f "$LAUNCH_VARS" ]; then
		set -a
		source "$LAUNCH_VARS"
		set +a
	else
		echo "ERROR: Launch variables file not found: $LAUNCH_VARS" >&2
		exit 1
	fi
}

validate_paths() {
	if [ ! -f "$LAUNCHER_EXE" ]; then
		echo "ERROR: Launcher executable not found: $LAUNCHER_EXE" >&2
		exit 1
	fi

	if [ ! -x "%s" ]; then
		echo "ERROR: %s not found or not executable" >&2
		exit 1
	fi
}

run_launcher() {
	cd "$GAME_DIR" || exit 1
	LOG_FILE="$GAME_DIR/launcher.log"

	%s "-k"
	sleep 1

	%s run "$LAUNCHER_EXE" "$@" > "$LOG_FILE" 2>> "$LOG_FILE"

	return "$?"
}

main() {
	load_launch_vars
	validate_paths
	run_launcher "$@"
	exit $?
}

main "$@"
`, wineprefix, wineprefix,
		LauncherExePath(wineprefix),
		protonBin,
		protonBin, protonBin,
		wineserverBin, protonBin), nil
}

// LaunchVarsEnvContent returns the content for the launch_vars.env file.
func LaunchVarsEnvContent(gpuType string) (string, error) {
	// Validate GPU type
	if gpuType != "AMD" && gpuType != "NVIDIA" {
		return "", fmt.Errorf("invalid GPU type: %s", gpuType)
	}

	return fmt.Sprintf(`# Bellum Launch Variables (%s)
# Auto-generated by Bellum Linux Installer

export __GAMESCOPE_INTEGRATION=""
export __GAMESCOPE_INTEGRATION_FORCE="0"
export __GAMESCOPE_INTEGRATION_GAMER_MODE="0"
export NVAPI_OVERRIDE_CONFIG=""
export NVVM_LIBDIR="${PROTONPATH}/nvvm/lib64"
export LD_LIBRARY_PATH="${PROTONPATH}/lib64:${LD_LIBRARY_PATH}"
`, gpuType), nil
}

// ValidateLauncherEnvironment checks that all required files exist for the launcher to work.
func ValidateLauncherEnvironment(wineprefix string) error {
	// Check launch_vars.env
	if _, err := os.Stat(filepath.Join(wineprefix, "launch_vars.env")); err != nil {
		return fmt.Errorf("launch variables file not found: %w", err)
	}

	// Check launcher executable
	launcherExe := LauncherExePath(wineprefix)
	if _, err := os.Stat(launcherExe); err != nil {
		return fmt.Errorf("launcher executable not found: %s: %w", launcherExe, err)
	}

	// Check WINEPREFIX exists
	if _, err := os.Stat(wineprefix); err != nil {
		return fmt.Errorf("WINEPREFIX not found: %s: %w", wineprefix, err)
	}

	return nil
}

// GetDesktopFileTemplate returns the .desktop file content for the given GPU type.
func GetDesktopFileTemplate(entryName, entryExec, entryComment, installedIcon, wineprefix string) string {
	return fmt.Sprintf(`[Desktop Entry]
Name=%s
Comment=%s
Exec=%s
Icon=%s
Type=Application
Categories=Game;
Terminal=false
Path=%s
`, entryName, entryComment, entryExec, installedIcon, wineprefix)
}

// IsGioAvailable checks if the gio command is available.
func IsGioAvailable() bool {
	return core.LookPath("gio") != ""
}

// IsUpdateDesktopDatabaseAvailable checks if update-desktop-database is available.
func IsUpdateDesktopDatabaseAvailable() bool {
	return core.LookPath("update-desktop-database") != ""
}

// MarkDesktopTrusted marks a .desktop file as trusted using gio.
func MarkDesktopTrusted(desktopFile string) error {
	if !IsGioAvailable() {
		return nil
	}
	return runGioSet(desktopFile, "metadata::trusted", "true")
}

// UpdateDesktopDatabase updates the desktop database for the given directory.
func UpdateDesktopDatabase(dir string) error {
	if !IsUpdateDesktopDatabaseAvailable() {
		return nil
	}
	return runUpdateDesktopDatabase(dir)
}

// EnsureLauncherDirectories creates all necessary directories for the launcher.
func EnsureLauncherDirectories() error {
	dirs := []string{
		"/usr/local/bin",
		"/usr/local/share/applications",
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}
	return nil
}

// EnsureUserLauncherDirectories creates user-level directories for icons and desktop files.
func EnsureUserLauncherDirectories() error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	dirs := []string{
		filepath.Join(homeDir, ".local", "share", "applications"),
		filepath.Join(homeDir, ".local", "share", "icons", "hicolor", "256x256", "apps"),
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}
	return nil
}

// RemoveLauncherDesktop removes the .desktop file.
// All GPU types produce Bellum.desktop.
func RemoveLauncherDesktop(gpuType string) error {
	desktopPath := LauncherDesktopPath(gpuType)
	if desktopPath == "" {
		return nil
	}
	if err := os.Remove(desktopPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove desktop file %s: %w", desktopPath, err)
	}

	// Also remove from ~/Desktop/ if it exists
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return nil // non-fatal
	}
	desktopDest := filepath.Join(homeDir, "Desktop", "Bellum.desktop")
	if err := os.Remove(desktopDest); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove desktop shortcut %s: %w", desktopDest, err)
	}

	return nil
}

// RemoveLauncherIcon removes the launcher icon.
func RemoveLauncherIcon() error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return nil // non-fatal
	}
	iconPath := filepath.Join(homeDir, ".local", "share", "icons", "hicolor", "256x256", "apps", "bellum.png")
	if err := os.Remove(iconPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove icon %s: %w", iconPath, err)
	}
	return nil
}

// RemoveLauncherBinary removes the launcher binary for the given GPU type.
func RemoveLauncherBinary(gpuType string) error {
	binaryPath := LauncherBinaryPath(gpuType)
	if binaryPath == "" {
		return nil
	}
	if err := os.Remove(binaryPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove launcher binary %s: %w", binaryPath, err)
	}
	return nil
}

// EnsureLaunchVarsEnv creates the launch_vars.env file in the WINEPREFIX.
func EnsureLaunchVarsEnv(wineprefix, gpuType string) error {
	content, err := LaunchVarsEnvContent(gpuType)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(wineprefix, "launch_vars.env"), []byte(content), 0644)
}

// EnsureLauncherWrapper installs the launcher wrapper script to /usr/local/bin/.
// Both GPU types write to /usr/local/bin/Bellum — NVIDIA uses proton wrapper,
// AMD uses wine wrapper.
func EnsureLauncherWrapper(gpuType, wineprefix, protonpath string) error {
	var scriptContent string
	var err error

	switch gpuType {
	case "AMD":
		scriptContent, err = GetLauncherScript(wineprefix, protonpath)
	case "NVIDIA":
		scriptContent, err = GetProtonLauncherScript(wineprefix, protonpath)
	default:
		return fmt.Errorf("unsupported GPU type: %s", gpuType)
	}

	if err != nil {
		return fmt.Errorf("failed to generate launcher script: %w", err)
	}

	scriptPath := "/usr/local/bin/Bellum"
	if err := os.WriteFile(scriptPath, []byte(scriptContent), 0755); err != nil {
		return fmt.Errorf("failed to write launcher script to %s: %w", scriptPath, err)
	}

	return nil
}

// EnsureLauncherDesktop creates the .desktop file for the given GPU type.
// Both GPU types use "Bellum" as the binary and desktop name.
func EnsureLauncherDesktop(gpuType, wineprefix, iconPath string) error {
	if err := EnsureUserLauncherDirectories(); err != nil {
		return err
	}

	entryName := "Bellum"
	entryExec := "Bellum"
	var entryComment string
	switch gpuType {
	case "AMD":
		entryComment = "Launch Bellum via Wine"
	case "NVIDIA":
		entryComment = "Launch Bellum via Proton (NVIDIA optimized)"
	default:
		return fmt.Errorf("unsupported GPU type: %s", gpuType)
	}

	installedIcon := iconPath
	if installedIcon == "" {
		homeDir, err := os.UserHomeDir()
		if err == nil {
			installedIcon = filepath.Join(homeDir, ".local", "share", "icons", "hicolor", "256x256", "apps", "bellum.png")
		}
	}

	desktopContent := GetDesktopFileTemplate(entryName, entryExec, entryComment, installedIcon, wineprefix)
	desktopPath := filepath.Join(os.Getenv("HOME"), ".local", "share", "applications", entryName+".desktop")

	if err := os.WriteFile(desktopPath, []byte(desktopContent), 0755); err != nil {
		return fmt.Errorf("failed to write desktop file: %w", err)
	}

	// Copy to ~/Desktop/
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return nil // non-fatal: home dir unavailable
	}
	desktopDest := filepath.Join(homeDir, "Desktop", entryName+".desktop")
	if _, err := os.Stat(filepath.Join(homeDir, "Desktop")); err == nil {
		_ = copyFile(desktopPath, desktopDest)
	}

	// Mark as trusted
	if IsGioAvailable() {
		_ = MarkDesktopTrusted(desktopPath)
		if _, err := os.Stat(desktopDest); err == nil {
			_ = MarkDesktopTrusted(desktopDest)
		}
	}

	// Update desktop database
	if IsUpdateDesktopDatabaseAvailable() {
		_ = UpdateDesktopDatabase(filepath.Join(homeDir, ".local", "share", "applications"))
	}

	return nil
}

// EnsureLauncherIcon copies the launcher icon to the user's icon directory.
func EnsureLauncherIcon(iconPath string) error {
	if iconPath == "" {
		return nil // non-fatal: icon is optional
	}
	return CopyIcon(iconPath)
}

// IsLauncherFullyInstalled checks if all launcher components exist for the given GPU type.
func IsLauncherFullyInstalled(gpuType, wineprefix string) bool {
	// Check binary
	if !IsLauncherInstalled(gpuType) {
		return false
	}

	// Check desktop file
	desktopPath := LauncherDesktopPath(gpuType)
	if _, err := os.Stat(desktopPath); err != nil {
		return false
	}

	// Check launch_vars.env
	if _, err := os.Stat(filepath.Join(wineprefix, "launch_vars.env")); err != nil {
		return false
	}

	// Check launcher executable
	if _, err := os.Stat(LauncherExePath(wineprefix)); err != nil {
		return false
	}

	return true
}

// DetectLauncherType detects whether the installed launcher is a wine or proton wrapper.
// Both GPU types use /usr/local/bin/Bellum — detection is by content.
func DetectLauncherType() string {
	bellumPath := "/usr/local/bin/Bellum"
	if exists, _ := fileExists(bellumPath); !exists {
		return ""
	}
	content, err := os.ReadFile(bellumPath)
	if err != nil {
		return ""
	}
	// AMD wrapper uses wineboot + wine
	if strings.Contains(string(content), "wineboot") {
		return "AMD"
	}
	// NVIDIA wrapper uses proton run
	if strings.Contains(string(content), "proton run") {
		return "NVIDIA"
	}
	return ""
}

func fileExists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, err
}
