package launchers

import (
	"fmt"
	"io"
	"os"
	"os/user"
	"path/filepath"
	"strings"

	"bellum-installer/pkg/config"
	"bellum-installer/pkg/core"
)

// LauncherConfig holds configuration for launcher generation.
type LauncherConfig struct {
	Wineprefix         string
	Protonpath         string
	GPUType            string
	IconPath           string
	LauncherBinaryPath string
	UseProtonForAMD    bool
}

// GenerateLauncher generates the launcher wrapper scripts and desktop files.
func GenerateLauncher(config LauncherConfig, logger *core.Logger) error {
	if err := generateLauncherWrapper(config); err != nil {
		return fmt.Errorf("failed to generate launcher wrapper: %w", err)
	}

	if err := generateDesktopFiles(config, logger); err != nil {
		return fmt.Errorf("failed to generate desktop files: %w", err)
	}

	return nil
}

// generateLauncherWrapper creates the /usr/local/bin/Bellum wrapper script.
func generateLauncherWrapper(config LauncherConfig) error {
	script := generateWrapperContent(config)
	return writeWrapper(config.LauncherBinaryPath, script)
}

// generateWrapperContent builds the wrapper script content based on GPU type.
func generateWrapperContent(config LauncherConfig) string {
	launcherExe := LauncherExePath(config.Wineprefix)

	if config.GPUType == "AMD" && config.UseProtonForAMD {
		return generateNVIDIAWrapper(config.Wineprefix, launcherExe, config.Protonpath)
	}

	switch config.GPUType {
	case "AMD":
		return generateAMDWrapper(config.Wineprefix, launcherExe, config.Protonpath)
	case "NVIDIA":
		return generateNVIDIAWrapper(config.Wineprefix, launcherExe, config.Protonpath)
	}
	return generateAMDWrapper(config.Wineprefix, launcherExe, config.Protonpath)
}

// generateAMDWrapper generates the wrapper script for AMD GPUs.
func generateAMDWrapper(wineprefix, launcherExe, protonpath string) string {
	return fmt.Sprintf(`#!/bin/bash
# Bellum Launcher Wrapper
# Auto-generated by the Bellum Linux Installer

set -u

LAUNCH_VARS="%s/launch_vars.env"
GAME_DIR="%s"
LAUNCHER_EXE="%s"
PROTON_BIN="%s/proton"

load_launch_vars() {
  if [ -f "$LAUNCH_VARS" ]; then
    set -a
    source "$LAUNCH_VARS"
    set +a
  else
    echo "ERROR: Launch variables file not found: $LAUNCH_VARS" >&2
    exit 1
  fi
}

validate_paths() {
  if [ ! -f "$LAUNCHER_EXE" ]; then
    echo "ERROR: Launcher executable not found: $LAUNCHER_EXE" >&2
    exit 1
  fi

  if ! command -v wine &>/dev/null; then
    echo "ERROR: wine not found or not executable" >&2
    exit 1
  fi
}

run_launcher() {
  cd "$GAME_DIR" || exit 1
  LOG_FILE="$GAME_DIR/launcher.log"

  wineboot "--restart"
  sleep 1

  wine "$LAUNCHER_EXE" "$@" > "$LOG_FILE" 2>> "$LOG_FILE"

  wineboot "--end-session"

  return "$?"
}

main() {
  load_launch_vars
  validate_paths
  run_launcher "$@"
  exit $?
}

main "$@"
`, wineprefix, wineprefix, launcherExe, protonpath)
}

// generateNVIDIAWrapper generates the wrapper script for NVIDIA GPUs.
func generateNVIDIAWrapper(wineprefix, launcherExe, protonpath string) string {
	return fmt.Sprintf(`#!/bin/bash
# Bellum Proton Launcher Wrapper
# Auto-generated by the Bellum Linux Installer
# Optimized for NVIDIA GPUs

set -u

LAUNCH_VARS="%s/launch_vars.env"
GAME_DIR="%s"
LAUNCHER_EXE="%s"
PROTON_BIN="%s/proton"

load_launch_vars() {
  if [ -f "$LAUNCH_VARS" ]; then
    set -a
    source "$LAUNCH_VARS"
    set +a
  else
    echo "ERROR: Launch variables file not found: $LAUNCH_VARS" >&2
    exit 1
  fi
}

validate_paths() {
  if [ ! -f "$LAUNCHER_EXE" ]; then
    echo "ERROR: Launcher executable not found: $LAUNCHER_EXE" >&2
    exit 1
  fi

  if [ ! -x "%s" ]; then
    echo "ERROR: %s not found or not executable" >&2
    exit 1
  fi
}

run_launcher() {
  cd "$GAME_DIR" || exit 1
  LOG_FILE="$GAME_DIR/launcher.log"

  wineserver "-k"
  sleep 1

  "$PROTON_BIN" run "$LAUNCHER_EXE" "$@" > "$LOG_FILE" 2>> "$LOG_FILE"

  return "$?"
}

main() {
  load_launch_vars
  validate_paths
  run_launcher "$@"
  exit $?
}

main "$@"
`, wineprefix, wineprefix, launcherExe, protonpath, protonpath, protonpath)
}

// writeWrapper writes a wrapper script to the specified path.
// If writing to the launcher bin directory and not running as root, it uses pkexec.
func writeWrapper(path, content string) error {
	dir := filepath.Dir(path)

	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	if os.Geteuid() != 0 && strings.HasPrefix(path, config.LauncherBinDir+"/") {
		return writeWrapperWithSudo(path, content)
	}

	if err := os.WriteFile(path, []byte(content), 0755); err != nil {
		return fmt.Errorf("failed to write wrapper script: %w", err)
	}

	return nil
}

// writeWrapperWithSudo uses pkexec to write the file with elevated privileges.
func writeWrapperWithSudo(path, content string) error {
	currentUser, err := user.Current()
	if err != nil {
		return fmt.Errorf("failed to get current user: %w", err)
	}

	tmpFile, err := os.CreateTemp("", "bellum-launcher-*.sh")
	if err != nil {
		return fmt.Errorf("failed to create temporary file: %w", err)
	}
	tmpPath := tmpFile.Name()
	defer os.Remove(tmpPath)

	if _, err := tmpFile.WriteString(content); err != nil {
		tmpFile.Close()
		return fmt.Errorf("failed to write to temporary file: %w", err)
	}
	tmpFile.Close()

	cmd := []string{"pkexec", "cp", tmpPath, path}
	if err := core.RunCommand(core.RunModeStream, cmd, nil, ""); err != nil {
		return fmt.Errorf("failed to copy launcher with pkexec: %w", err)
	}

	cmd = []string{"pkexec", "chmod", "755", path}
	if err := core.RunCommand(core.RunModeStream, cmd, nil, ""); err != nil {
		return fmt.Errorf("failed to make launcher executable: %w", err)
	}

	chownArg := fmt.Sprintf("%s:%s", currentUser.Username, currentUser.Username)
	cmd = []string{"pkexec", "chown", chownArg, path}
	if err := core.RunCommand(core.RunModeStream, cmd, nil, ""); err != nil {
		return fmt.Errorf("failed to change launcher ownership: %w", err)
	}

	return nil
}

// generateDesktopFiles creates the .desktop files and icon for the launcher.
func generateDesktopFiles(config LauncherConfig, logger *core.Logger) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get user home directory: %w", err)
	}

	appsDir := filepath.Join(homeDir, ".local", "share", "applications")
	appsIconDir := filepath.Join(homeDir, ".local", "share", "icons", "hicolor", "256x256", "apps")

	var entryComment string
	switch config.GPUType {
	case "AMD":
		entryComment = "Launch Bellum via Wine"
	case "NVIDIA":
		entryComment = "Launch Bellum via Proton (NVIDIA optimized)"
	default:
		return fmt.Errorf("unsupported GPU type for desktop file: %s", config.GPUType)
	}

	entryName := "Bellum"

	installedIcon := ""
	if config.IconPath != "" {
		if err := os.MkdirAll(appsIconDir, 0755); err != nil {
			return fmt.Errorf("failed to create icon directory: %w", err)
		}
		iconDest := filepath.Join(appsIconDir, "bellum.png")
		if err := copyFile(config.IconPath, iconDest); err != nil {
			return fmt.Errorf("failed to copy icon: %w", err)
		}
		installedIcon = iconDest
	}

	desktopFile := filepath.Join(appsDir, "Bellum.desktop")
	desktopContent := fmt.Sprintf(`[Desktop Entry]
Name=%s
Comment=%s
Exec=%s
Icon=%s
Type=Application
Categories=Game;
Terminal=false
Path=%s
`, entryName, entryComment, entryName, installedIcon, config.Wineprefix)

	if err := os.WriteFile(desktopFile, []byte(desktopContent), 0755); err != nil {
		return fmt.Errorf("failed to write desktop file %s: %w", desktopFile, err)
	}

	// Copy to ~/Desktop/
	desktopDest := filepath.Join(homeDir, "Desktop", fmt.Sprintf("%s.desktop", entryName))
	desktopDir := filepath.Join(homeDir, "Desktop")
	if err := os.MkdirAll(desktopDir, 0755); err != nil {
		logger.Warn(fmt.Sprintf("Failed to create desktop directory: %v", err))
	} else {
		if err := copyFile(desktopFile, desktopDest); err != nil {
			logger.Warn(fmt.Sprintf("Failed to copy desktop file to desktop: %v", err))
		} else {
			if err := os.Chmod(desktopDest, 0755); err != nil {
				logger.Warn(fmt.Sprintf("Failed to set desktop shortcut permissions: %v", err))
			}
		}
	}

	if err := runGioSet(desktopFile, "metadata::trusted", "true", logger); err != nil {
		logger.Warn(fmt.Sprintf("Failed to mark desktop file as trusted: %v", err))
	}
	if _, err := os.Stat(desktopDest); err == nil {
		if err := runGioSet(desktopDest, "metadata::trusted", "true", logger); err != nil {
			logger.Warn(fmt.Sprintf("Failed to mark desktop shortcut as trusted: %v", err))
		}
	}

	if err := runUpdateDesktopDatabase(appsDir, logger); err != nil {
		logger.Warn(fmt.Sprintf("Failed to update desktop database: %v", err))
	}

	return nil
}

// runGioSet runs gio set to set a metadata key on a file.
func runGioSet(file, key, value string, logger *core.Logger) error {
	return core.RunCommand(core.RunModeSilent, []string{"gio", "set", file, key, value}, logger, "")
}

// runUpdateDesktopDatabase runs update-desktop-database for the given directory.
func runUpdateDesktopDatabase(dir string, logger *core.Logger) error {
	return core.RunCommand(core.RunModeSilent, []string{"update-desktop-database", dir}, logger, "")
}

// copyFile copies a file from src to dst.
func copyFile(src, dst string) error {
	source, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("failed to open source file: %w", err)
	}
	defer source.Close()

	destination, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("failed to create destination file: %w", err)
	}
	defer destination.Close()

	if _, err := io.Copy(destination, source); err != nil {
		os.Remove(dst)
		return fmt.Errorf("failed to copy file: %w", err)
	}

	if err := destination.Close(); err != nil {
		os.Remove(dst)
		return fmt.Errorf("failed to close destination file: %w", err)
	}

	return nil
}

// CopyIcon copies the launcher icon to the user's local icon directory.
func CopyIcon(iconPath string) error {
	if iconPath == "" {
		return fmt.Errorf("icon path is empty")
	}

	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get user home directory: %w", err)
	}

	iconDest := filepath.Join(homeDir, ".local", "share", "icons", "hicolor", "256x256", "apps", "bellum.png")
	if err := os.MkdirAll(filepath.Dir(iconDest), 0755); err != nil {
		return fmt.Errorf("failed to create icon directory: %w", err)
	}

	return copyFile(iconPath, iconDest)
}

// CreateLaunchVarsFileNvidia creates the launch environment file for NVIDIA GPUs.
func CreateLaunchVarsFileNvidia(wineprefix, protonpath string, logger *core.Logger) error {
	launchVars := filepath.Join(wineprefix, "launch_vars.env")
	logger.Info(fmt.Sprintf("Creating launch environment file: %s", launchVars))

	content := `# Bellum Launch Variables (NVIDIA)
# Auto-generated by Bellum Linux Installer

PROTONPATH="` + protonpath + `"
WINEPREFIX="` + wineprefix + `"
STEAM_COMPAT_DATA_PATH="` + wineprefix + `"
STEAM_COMPAT_SHADER_PATH="shadercache"
STEAM_COMPAT_CLIENT_INSTALL_PATH=""
PROTON_ENABLE_NGX_UPDATER="1"
PROTON_ENABLE_NVAPI="1"
PROTON_VKD3D_HEAP="1"
PROTON_DXVK_D3D8="1"
PROTON_NVIDIA_LIBS="1"
PROTON_DLSS_UPGRADE="1"
MALLOC_ARENA_MAX="1"
VKD3D_CONFIG="descriptor_heap"
WINEESYNC="1"
WINEFSYNC="1"
DXVK_NVAPI="1"
DXVK_ENABLE_NVAPI="1"
DXVK_NVAPIHACK="0"
WEBKIT_DISABLE_DMABUF_RENDERER="1"
WINE_LARGE_ADDRESS_AWARE="1"
CUDA_DISABLE_PERF_BOOST="1"
`

	if err := os.WriteFile(launchVars, []byte(content), 0644); err != nil {
		return err
	}

	logger.Info("[OK] Launch environment file created")
	return nil
}

// CreateLaunchVarsFileAMD creates the launch environment file for AMD GPUs.
func CreateLaunchVarsFileAMD(wineprefix, protonpath string, logger *core.Logger) error {
	launchVars := filepath.Join(wineprefix, "launch_vars.env")
	logger.Info(fmt.Sprintf("Creating launch environment file: %s", launchVars))
	fsr4Ver := "1"
	content := fmt.Sprintf(`# Bellum Launch Variables (AMD)
# Auto-generated by Bellum Linux Installer
STEAM_COMPAT_DATA_PATH="`+wineprefix+`"
STEAM_COMPAT_CLIENT_INSTALL_PATH=""
PROTONPATH="%s"
WINEPREFIX="%s"
FSR4_UPGRADE="%s"
FSR4_RDNA3_UPGRADE="%s"
PROTON_MLFG_UPGRADE="1"
PROTON_VKD3D_HEAP="1"
VKD3D_CONFIG="descriptor_heap"
WINE_LARGE_ADDRESS_AWARE="1"
`, protonpath, wineprefix, fsr4Ver, fsr4Ver)

	if err := os.WriteFile(launchVars, []byte(content), 0644); err != nil {
		return err
	}

	logger.Info("[OK] Launch environment file created")
	return nil
}

// IsLauncherInstalled checks if the launcher binary exists.
func IsLauncherInstalled() bool {
	_, err := os.Stat(config.LauncherBinaryPath)
	return err == nil
}

// LauncherDesktopPath returns the full path to the .desktop file.
func LauncherDesktopPath(homeDir string) string {
	return filepath.Join(homeDir, ".local", "share", "applications", "Bellum.desktop")
}

// LauncherIconPath returns the full path to the launcher icon.
func LauncherIconPath(homeDir string) string {
	return filepath.Join(homeDir, config.UserIconsDir, config.LauncherIconName)
}

// LaunchVarsEnvPath returns the path to the launch_vars.env file.
func LaunchVarsEnvPath(wineprefix string) string {
	return filepath.Join(wineprefix, "launch_vars.env")
}

// LauncherExePath returns the path to the AstarteLauncher.exe inside WINEPREFIX.
func LauncherExePath(wineprefix string) string {
	return filepath.Join(wineprefix, "drive_c/users/steamuser/AppData/Local/Astarte Industries/Astarte Launcher/AstarteLauncher.exe")
}

// LauncherLogPath returns the path to the launcher.log file.
func LauncherLogPath(wineprefix string) string {
	return filepath.Join(wineprefix, "launcher.log")
}

// EnsureWineBinaries checks that wine, wineboot, and wineserver are available.
func EnsureWineBinaries() (wine, wineboot, wineserver string, err error) {
	wine = core.LookPath("wine")
	if wine == "" {
		return "", "", "", fmt.Errorf("wine not found")
	}
	wineboot = core.LookPath("wineboot")
	if wineboot == "" {
		return "", "", "", fmt.Errorf("wineboot not found")
	}
	wineserver = core.LookPath("wineserver")
	if wineserver == "" {
		return "", "", "", fmt.Errorf("wineserver not found")
	}
	return wine, wineboot, wineserver, nil
}

// EnsureProtonBinary checks that the proton binary exists and is executable.
func EnsureProtonBinary(protonpath string) error {
	protonBin := filepath.Join(protonpath, "proton")
	if _, err := os.Stat(protonBin); err != nil {
		return fmt.Errorf("proton binary not found at %s: %w", protonBin, err)
	}
	if err := os.Chmod(protonBin, 0755); err != nil {
		return fmt.Errorf("failed to make proton binary executable: %w", err)
	}
	return nil
}

// ValidateLauncherEnvironment checks that all required files exist for the launcher to work.
func ValidateLauncherEnvironment(wineprefix string) error {
	if _, err := os.Stat(filepath.Join(wineprefix, "launch_vars.env")); err != nil {
		return fmt.Errorf("launch variables file not found: %w", err)
	}

	launcherExe := LauncherExePath(wineprefix)
	if _, err := os.Stat(launcherExe); err != nil {
		return fmt.Errorf("launcher executable not found: %s: %w", launcherExe, err)
	}

	if _, err := os.Stat(wineprefix); err != nil {
		return fmt.Errorf("WINEPREFIX not found: %s: %w", wineprefix, err)
	}

	return nil
}

// RemoveLauncherDesktop removes the .desktop file.
// All GPU types produce Bellum.desktop.
func RemoveLauncherDesktop() error {
	homeDir := os.Getenv("HOME")
	paths := config.GetLauncherPaths("", homeDir)
	desktopPath := paths.DesktopPath

	if err := os.Remove(desktopPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove desktop file %s: %w", desktopPath, err)
	}

	desktopDest := config.DesktopLauncherPath(homeDir)
	if err := os.Remove(desktopDest); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove desktop shortcut %s: %w", desktopDest, err)
	}

	return nil
}

// RemoveLauncherIcon removes the launcher icon.
func RemoveLauncherIcon() error {
	iconPath := filepath.Join(os.Getenv("HOME"), ".local", "share", "icons", "hicolor", "256x256", "apps", "bellum.png")
	if err := os.Remove(iconPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove icon %s: %w", iconPath, err)
	}
	return nil
}

// RemoveLauncherBinary removes the launcher binary.
// If running as a non-root user and the path is under /usr/local/bin, it uses pkexec.
func RemoveLauncherBinary() error {
	binaryPath := config.LauncherBinaryPath
	if _, err := os.Stat(binaryPath); os.IsNotExist(err) {
		return nil
	}
	if err := os.Remove(binaryPath); err != nil {
		if os.IsPermission(err) && strings.HasPrefix(binaryPath, config.LauncherBinDir+"/") {
			cmd := []string{"pkexec", "rm", binaryPath}
			if err := core.RunCommand(core.RunModeStream, cmd, nil, ""); err != nil {
				return fmt.Errorf("failed to remove %s with pkexec: %w", binaryPath, err)
			}
			return nil
		}
		return fmt.Errorf("failed to remove launcher binary %s: %w", binaryPath, err)
	}
	return nil
}

// IsLauncherFullyInstalled checks if all launcher components exist.
func IsLauncherFullyInstalled(wineprefix string) bool {
	if !IsLauncherInstalled() {
		return false
	}

	homeDir, err := os.UserHomeDir()
	if err != nil {
		return false
	}

	desktopPath := LauncherDesktopPath(homeDir)
	if _, err := os.Stat(desktopPath); err != nil {
		return false
	}

	if _, err := os.Stat(filepath.Join(wineprefix, "launch_vars.env")); err != nil {
		return false
	}

	if _, err := os.Stat(LauncherExePath(wineprefix)); err != nil {
		return false
	}

	return true
}
