package workflow

import (
	"fmt"
	"os"
	"path/filepath"

	cfg "bellum-installer/pkg/config"
	"bellum-installer/pkg/core"
)

// ConfigureConfig holds configuration for post-install configuration
type ConfigureConfig struct {
	WINEPREFIX string
	ProtonPath string
	GPUType    string
	IsAMDGPU   bool
	Workdir    string
	IsFSR41    bool
}

// RunConfiguration runs the post-install configuration phase
func RunConfiguration(config ConfigureConfig, logger *core.Logger) error {
	fmt.Println()
	logger.Info("Starting configuration phase...")

	// Update DLL overrides
	if err := UpdateDLLs(logger); err != nil {
		return err
	}

	// GPU-specific configuration
	if config.GPUType == "NVIDIA" {
		if err := CreateLaunchVarsFileNvidia(config.WINEPREFIX, config.ProtonPath, logger); err != nil {
			return err
		}
		// dxvk_nvapi is included in Proton for NVIDIA
	} else if config.GPUType == "AMD" {
		// Only run UpgradeFSR when --fsr41 flag is passed
		if config.IsFSR41 {
			if err := UpgradeFSR(config, logger); err != nil {
				return err
			}
		}
		if err := CreateLaunchVarsFileAMD(config.WINEPREFIX, config.ProtonPath, config.IsFSR41, logger); err != nil {
			return err
		}
	} else {
		logger.Warn(fmt.Sprintf("Unknown or unsupported GPU type: %s", config.GPUType))
	}

	logger.Info("[OK] Configuration phase complete!")
	fmt.Println()

	return nil
}

// UpdateDLLs sets up DLL overrides for the WINEPREFIX
func UpdateDLLs(logger *core.Logger) error {
	logger.Info("Setting DLL overrides")

	wine := cfg.DefaultVersions.Binaries.Wine
	logFile := ""

	// System-wide overrides
	systemDLLs := []string{
		"d3d12",
		"d3d12core",
		"d3d10core",
		"d3d9",
		"d3d8",
	}

	for _, dll := range systemDLLs {
		if err := core.RunCommand(core.RunModeSilent, []string{wine, "reg", "add", `HKEY_CURRENT_USER\Software\Wine\DllOverrides`, "/v", dll, "/d", "native,builtin", "/f"}, logger, logFile); err != nil {
			logger.Error(fmt.Sprintf("Failed to set override for %s", dll))
			return err
		}
	}

	// Application-specific overrides for d3d11 and dxgi
	appDLLs := []string{"d3d11", "dxgi"}

	for _, dll := range appDLLs {
		// Launcher overrides
		if err := core.RunCommand(core.RunModeSilent, []string{wine, "reg", "add", `HKCU\Software\Wine\AppDefaults\AstarteLauncher.exe\DllOverrides`, "/v", dll, "/d", "builtin", "/f"}, logger, logFile); err != nil {
			logger.Error(fmt.Sprintf("Failed to set override for %s (launcher)", dll))
			return err
		}

		// Game overrides
		if err := core.RunCommand(core.RunModeSilent, []string{wine, "reg", "add", `HKCU\Software\Wine\AppDefaults\Bellum-Win64-Shipping.exe\DllOverrides`, "/v", dll, "/d", "native", "/f"}, logger, logFile); err != nil {
			logger.Error(fmt.Sprintf("Failed to set override for %s (game)", dll))
			return err
		}
	}

	return nil
}

// CreateLaunchVarsFileNvidia creates the launch environment file for NVIDIA GPUs
func CreateLaunchVarsFileNvidia(wineprefix, protonpath string, logger *core.Logger) error {
	launchVars := filepath.Join(wineprefix, "launch_vars.env")
	logger.Info(fmt.Sprintf("Creating launch environment file: %s", launchVars))

	content := `# Bellum Launch Variables (NVIDIA)
# Auto-generated by Bellum Linux Installer

export PROTONPATH="` + protonpath + `"
export WINEPREFIX="` + wineprefix + `"
export STEAM_COMPAT_DATA_PATH="` + wineprefix + `"
export STEAM_COMPAT_SHADER_PATH="shadercache"
export STEAM_COMPAT_CLIENT_INSTALL_PATH=""
export PROTON_ENABLE_NGX_UPDATER="1"
export PROTON_ENABLE_NVAPI="1"
export PROTON_VKD3D_HEAP="1"
export PROTON_DXVK_D3D8="1"
export PROTON_NVIDIA_LIBS="1"
export PROTON_DLSS_UPGRADE="1"
export MALLOC_ARENA_MAX="1"
export VKD3D_CONFIG="descriptor_heap"
export WINEESYNC="1"
export WINEFSYNC="1"
export DXVK_NVAPI="1"
export DXVK_ENABLE_NVAPI="1"
export DXVK_NVAPIHACK="0"
export WEBKIT_DISABLE_DMABUF_RENDERER="1"
export WINE_LARGE_ADDRESS_AWARE="1"
export CUDA_DISABLE_PERF_BOOST="1"
`

	if err := os.WriteFile(launchVars, []byte(content), 0644); err != nil {
		logger.Error(fmt.Sprintf("Failed to create launch vars file: %v", err))
		return err
	}

	logger.Info("[OK] Launch environment file created")
	return nil
}

// CreateLaunchVarsFileAMD creates the launch environment file for AMD GPUs
func CreateLaunchVarsFileAMD(wineprefix, protonpath string, isFSR41 bool, logger *core.Logger) error {
	launchVars := filepath.Join(wineprefix, "launch_vars.env")
	logger.Info(fmt.Sprintf("Creating launch environment file: %s", launchVars))

	// Determine FSR4 values based on mode
	fsr4Upgrade := "1"
	fsr4Rdna3Upgrade := "1"
	if isFSR41 {
		fsr4Upgrade = "4.1.0"
		fsr4Rdna3Upgrade = "4.1.0"
	}

	content := `# Bellum Launch Variables (AMD)
# Auto-generated by Bellum Linux Installer

export PROTONPATH="` + protonpath + `"
export WINEPREFIX="` + wineprefix + `"
export FSR4_UPGRADE="` + fsr4Upgrade + `"
export FSR4_RDNA3_UPGRADE="` + fsr4Rdna3Upgrade + `"
export PROTON_VKD3D_HEAP="1"
export VKD3D_CONFIG="descriptor_heap"
export WINE_LARGE_ADDRESS_AWARE="1"
export DXIL_SPIRV_CONFIG=wmma_rdna3_workaround
`

	if err := os.WriteFile(launchVars, []byte(content), 0644); err != nil {
		logger.Error(fmt.Sprintf("Failed to create launch vars file: %v", err))
		return err
	}

	logger.Info("[OK] Launch environment file created")
	return nil
}

// UpgradeFSR upgrades to FSR 4.1.0 for AMD GPUs
func UpgradeFSR(config ConfigureConfig, logger *core.Logger) error {
	logger.Info("Upgrading to FSR 4.1.0")

	fsPath := filepath.Join(config.Workdir, "packages", "fsr4")
	if _, err := os.Stat(fsPath); os.IsNotExist(err) {
		logger.Warn(fmt.Sprintf("FSR 4.1.0 directory not found: %s, skipping upgrade", fsPath))
		return nil
	}

	fgDLL := "amd_fidelityfx_framegeneration_dx12.dll"
	d3DLL := "D3D12Core.dll"

	// Determine target directories
	progFiles := `Program Files`
	winePrefix := os.Getenv("WINEPREFIX")
	if winePrefix == "" {
		winePrefix = config.WINEPREFIX
	}

	fgTargetDir := filepath.Join(winePrefix, "drive_c", progFiles, "Astarte Industries", "Bellum", "Project_Bellum", "Plugins", "AMD", "FSR", "Source", "fidelityfx-sdk", "Kits", "FidelityFX", "signedbin")
	d3dTargetDir := filepath.Join(winePrefix, "drive_c", progFiles, "Astarte Industries", "Bellum", "Project_Bellum", "Binaries", "Win64", "D3D12", "x64")

	fgTarget := filepath.Join(fgTargetDir, fgDLL)
	d3dTarget := filepath.Join(d3dTargetDir, d3DLL)

	fgSource := filepath.Join(fsPath, fgDLL)
	d3dSource := filepath.Join(fsPath, d3DLL)

	// Get log file path
	logFile := filepath.Join(config.Workdir, "logs", "installer.log")

	// Create target directories
	core.RunCommand(core.RunModeSilent, []string{"mkdir", "-p", fgTargetDir, d3dTargetDir}, logger, logFile)

	// Copy FSR DLLs
	if _, err := os.Stat(fgSource); err == nil {
		if err := copyFile(fgSource, fgTarget); err != nil {
			logger.Error(fmt.Sprintf("Failed to copy %s -> %s", fgSource, fgTarget))
		} else {
			logger.Info(fmt.Sprintf("[OK] Copied %s", fgDLL))
		}
	}

	if _, err := os.Stat(d3dSource); err == nil {
		if err := copyFile(d3dSource, d3dTarget); err != nil {
			logger.Error(fmt.Sprintf("Failed to copy %s -> %s", d3dSource, d3dTarget))
		} else {
			logger.Info(fmt.Sprintf("[OK] Copied %s", d3DLL))
		}
	}

	// Register DLL override for amdxcffx64
	core.RunCommand(core.RunModeSilent, []string{cfg.DefaultVersions.Binaries.Wine, "reg", "add", `HKEY_CURRENT_USER\Software\Wine\DllOverrides`, "/v", "amdxcffx64", "/d", "native", "/f"}, logger, "")

	logger.Info("FSR 4.1.0 Upgrade Complete!")
	return nil
}

// copyFile copies a file from src to dst
func copyFile(src, dst string) error {
	source, err := os.Open(src)
	if err != nil {
		return err
	}
	defer source.Close()

	destination, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer destination.Close()

	_, err = destination.ReadFrom(source)
	return err
}
