#!/usr/bin/env bash
# Desktop launcher generator for Bellum Installer

# Do not redefine SCRIPT_DIR - it's defined in the main script

generate_launcher_executable() {
    local wineprefix="${1:-$WINEPREFIX}"
    local protonpath="${2:-$PROTONPATH}"

    if [ -z "$wineprefix" ] || [ -z "$protonpath" ]; then
        log error "generate_launcher_executable: WINEPREFIX and PROTONPATH are required"
        return 1
    fi

    local launcher_exe="${wineprefix}/drive_c/users/steamuser/AppData/Local/Astarte Industries/Astarte Launcher/AstarteLauncher.exe"
    local proton_bin="${protonpath}/proton"
    local icon_source="${WORKDIR}/packages/launcher_1_256x256x32.png"
    local wine_bin="$(command -v wine)"
    local wineserver_bin="$(command -v wineserver)"
    local wineboot_bin="$(command -v wineboot)"

    local gpu_type
    gpu_type=$(detect_gpu_type) || {
        log error "Failed to detect GPU type"
        return 1
    }
    
    log info "Detected GPU type: ${gpu_type}"

    local system_bin="/usr/local/bin"
    local bellum_script="${system_bin}/Bellum"
    local bellum_proton_script="${system_bin}/Bellum-Proton"

    log info "Generating system launcher: ${bellum_script}"

    local tmp_file
    tmp_file="$(mktemp)"
    trap 'rm -f "$tmp_file"' EXIT

    cat > "$tmp_file" <<WRAPPER_EOF
#!/usr/bin/env bash
# Bellum Launcher Wrapper
# Auto-generated by the Bellum Linux Installer

set -u

LAUNCH_VARS="${wineprefix}/launch_vars.env"
GAME_DIR="${wineprefix}"
LAUNCHER_EXE="${wineprefix}/drive_c/users/steamuser/AppData/Local/Astarte Industries/Astarte Launcher/AstarteLauncher.exe"
PROTON_BIN="${proton_bin}"

load_launch_vars() {
    if [ -f "\$LAUNCH_VARS" ]; then
        set -a
        source "\$LAUNCH_VARS"
        set +a
    else
        echo "ERROR: Launch variables file not found: \$LAUNCH_VARS" >&2
        exit 1
    fi
}

validate_paths() {
    if [ ! -f "\$LAUNCHER_EXE" ]; then
        echo "ERROR: Launcher executable not found: \$LAUNCHER_EXE" >&2
        exit 1
    fi

    if [ ! -x "${wine_bin}" ]; then
        echo "ERROR: ${wine_bin} not found or not executable" >&2
        exit 1
    fi
}

run_launcher() {
    cd "\$GAME_DIR" || exit 1
    LOG_FILE="\$GAME_DIR/launcher.log"

    "${wineboot_bin}" "--restart"
    sleep 1

    "${wine_bin}" "\$LAUNCHER_EXE" "\$@" > "\$LOG_FILE" 2>> "\$LOG_FILE"

    "${wineboot_bin}" "--end-session"

    return "\$?"
}

main() {
    load_launch_vars
    validate_paths
    run_launcher "\$@"
    exit \$?
}

main "\$@"
WRAPPER_EOF

    if ! sudo mv "$tmp_file" "$bellum_script"; then
        log error "Failed to install launcher to ${system_bin} (sudo required)"
        rm -f "$tmp_file"
        return 1
    fi
    sudo chmod +x "$bellum_script"

    log info "✓ Game launcher installed: ${bellum_script}"

    local apps_icon_dir="$HOME/.local/share/icons/hicolor/256x256/apps"
    mkdir -p "$apps_icon_dir"

    local installed_icon=""
    if [ -f "$icon_source" ]; then
        cp "$icon_source" "${apps_icon_dir}/bellum.png"
        installed_icon="${apps_icon_dir}/bellum.png"
        log info "✓ Icon installed to ${installed_icon}"
    else
        log warn "No launcher icon available"
    fi

    local apps_dir="$HOME/.local/share/applications"
    mkdir -p "$apps_dir"

    generate_desktop_entry() {
        local entry_name="$1"
        local entry_exec="$2"
        local entry_icon="${3:-$installed_icon}"
        local entry_comment="${4:-Launch Bellum via Wine}"
        local desktop_file="${apps_dir}/${entry_name}.desktop"

        log info "Generating applications menu entry: ${desktop_file}"

        cat > "$desktop_file" <<DESKTOP_EOF
[Desktop Entry]
Name=${entry_name}
Comment=${entry_comment}
Exec=${entry_exec}
Icon=${entry_icon}
Type=Application
Categories=Game;
Terminal=false
Path=${wineprefix}
DESKTOP_EOF

        chmod +x "$desktop_file"

        local desktop_dest="$HOME/Desktop/${entry_name}.desktop"
        if [ -d "$HOME/Desktop" ]; then
            cp "$desktop_file" "$desktop_dest"
            chmod +x "$desktop_dest"
            log info "✓ Desktop entry copied to ${desktop_dest}"
        else
            log warn "Desktop directory not found at ~/Desktop — skipping desktop shortcut"
        fi

        if command -v gio &>/dev/null; then
            gio set "$desktop_file" metadata::trusted true 2>/dev/null || true
            if [ -f "$desktop_dest" ]; then
                gio set "$desktop_dest" metadata::trusted true 2>/dev/null || true
            fi
            log info "✓ Desktop entries marked as trusted"
        else
            log warn "gio not found — desktop entries may show as untrusted"
        fi

        if command -v update-desktop-database &>/dev/null; then
            update-desktop-database "$apps_dir" 2>/dev/null || true
        fi

        log info "✓ Applications menu entry created: ${desktop_file}"
    }

    generate_desktop_entry "Bellum" "$bellum_script" "$installed_icon" "Launch Bellum via Wine"

    # For NVIDIA GPUs, also create Bellum-Proton wrapper
    if [ "$gpu_type" = "NVIDIA" ]; then
        log info "Creating NVIDIA-optimized launcher: ${bellum_proton_script}"
        
        cat > "$tmp_file" <<PROTON_WRAPPER_EOF
#!/usr/bin/env bash
# Bellum Proton Launcher Wrapper
# Auto-generated by the Bellum Linux Installer
# Optimized for NVIDIA GPUs

set -u

LAUNCH_VARS="${wineprefix}/launch_vars.env"
GAME_DIR="${wineprefix}"
LAUNCHER_EXE="${wineprefix}/drive_c/users/steamuser/AppData/Local/Astarte Industries/Astarte Launcher/AstarteLauncher.exe"
PROTON_BIN="${proton_bin}"

load_launch_vars() {
    if [ -f "\$LAUNCH_VARS" ]; then
        set -a
        source "\$LAUNCH_VARS"
        set +a
    else
        echo "ERROR: Launch variables file not found: \$LAUNCH_VARS" >&2
        exit 1
    fi
}

validate_paths() {
    if [ ! -f "\$LAUNCHER_EXE" ]; then
        echo "ERROR: Launcher executable not found: \$LAUNCHER_EXE" >&2
        exit 1
    fi

    if [ ! -x "${proton_bin}" ]; then
        echo "ERROR: ${proton_bin} not found or not executable" >&2
        exit 1
    fi
}

run_launcher() {
    cd "\$GAME_DIR" || exit 1
    LOG_FILE="\$GAME_DIR/launcher.log"

    "${wineserver_bin}" "-k"
    sleep 1

    "${proton_bin}" run "\$LAUNCHER_EXE" "\$@" > "\$LOG_FILE" 2>> "\$LOG_FILE"

    return "\$?"
}

main() {
    load_launch_vars
    validate_paths
    run_launcher "\$@"
    exit \$?
}

main "\$@"
PROTON_WRAPPER_EOF

        if ! sudo mv "$tmp_file" "$bellum_proton_script"; then
            log error "Failed to install Proton launcher to ${system_bin} (sudo required)"
            rm -f "$tmp_file"
            return 1
        fi
        sudo chmod +x "$bellum_proton_script"

        log info "✓ Proton launcher installed: ${bellum_proton_script}"

        generate_desktop_entry "Bellum-Proton" "$bellum_proton_script" "$installed_icon" "Launch Bellum via Proton (NVIDIA optimized)"
    fi

    return 0
}
